<?php
// $Id$

/**
  * Campus Podcasts
  * Copyright (c) Tom Gillett 2011
  */

/* Implementation of hook_views_api(). */
function campus_podcasts_views_api() {
	return array(
		'api' => 3,
		'path' => drupal_get_path('module', 'campus_podcasts')
	);
}

/*Implements hook_views_default_views() */
function campus_podcasts_views_default_views() {
	include_once DRUPAL_ROOT . '/'. drupal_get_path('module', 'campus_homepage') .'/includes/definitions/'. 'views.campus_podcasts.inc';
	$views[$view->name] = $view;
	return $views;
}

/* Implements hook_cviews_title_replacement - as implemented by campus_homepage */
function campus_podcasts_cviews_title_replacement(){
	return array('campus_podcasts');
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function campus_podcasts_ctools_plugin_api($module, $api) {
	if($module == 'page_manager' && $api == 'pages_default') {
		return array('version' => 1);
	}
}

/**
 * Implementation of hook_default_page_manager_handlers()
function campus_podcasts_default_page_manager_handlers() {
	include_once './'. drupal_get_path('module', 'campus_homepage') .'/includes/definitions/page_manager_variant.campus_podcasts.inc';
	return $handlers;
}
 */
